manifest:
  remotes:
    - name: zmkfirmware
      url-base: github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: head
      import: app/west.yml
  self:
    path: config
